Repository DOCMM-Solucoes/facil_facil_hospedagem, pull requests merged in 2023-07, with the labels that each got.

#60 Devise tests
  Gemfile
  Gemfile.lock
  app/assets/builds/tailwind.css
  app/assets/stylesheets/application.tailwind.css
  app/javascript/application.js
  app/views/hoteliers/_form.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  config/application.rb
  config/locales/address/en.yml
  config/locales/address/pt-BR.yml
  config/tailwind.config.js
  package-lock.json
  package.json
  spec/controllers/trips_spec.rb
  spec/factories/address.rb
  spec/factories/establishments.rb
  spec/factories/hoteliers.rb
  spec/factories/users.rb
  spec/features/users_spec.rb
  spec/model/user_spec.rb
  spec/models/trip_spec.rb
  spec/rails_helper.rb
  spec/routes/users_spec.rb
  test/controllers/photos_controller_test.rb
  test/controllers/rooms_controller_test.rb
  test/fixtures/photos.yml
  test/fixtures/rooms.yml
  test/models/photo_test.rb
  test/models/room_test.rb
  test/system/photos_test.rb
  test/system/rooms_test.rb
  yarn.lock
Labels: enhancement, test

#63 Feature/trip tests
  Gemfile
  Gemfile.lock
  app/controllers/trips_controller.rb
  spec/controllers/trips_spec.rb
  spec/factories/guides.rb
  spec/factories/trips.rb
  spec/factories/users.rb
  spec/models/trip_spec.rb
  spec/rails_helper.rb
  spec/requests/trips_spec.rb
  spec/routings/trips_spec
Labels: test

#54 Test/rooms
  .env-example
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  docker-compose.yml
  spec/controllers/rooms_controller_spec.rb
  spec/factories/rooms.rb
  spec/models/room_spec.rb
  spec/rails_helper.rb
  spec/requests/rooms_spec.rb
  spec/routings/rooms_spec.rb
Labels: documentation, enhancement

#91 Feature/guide tests
  spec/controllers/guides_spec.rb
  spec/factories/address.rb
  spec/factories/addresses.rb
  spec/factories/guides.rb
  spec/models/guide_spec.rb
  spec/requests/guides_spec.rb
  spec/requests/rooms_spec.rb
  spec/requests/trips_spec.rb
  spec/routings/guides_spec.rb
  spec/routings/trips_spec.rb
Labels: test
