Repository DOCMM-Solucoes/facil_facil_hospedagem, pull requests merged in 2023-09, with the labels that each got.

#120 Feature/trip specific adjustments
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/assets/stylesheets/custom_styles.css
  app/models/guide.rb
  app/models/trip.rb
  app/views/guides/_form.html.erb
  app/views/guides/edit.html.erb
  app/views/guides/index.html.erb
  app/views/guides/new.html.erb
  app/views/guides/show.html.erb
  app/views/layouts/application.html.erb
  app/views/trips/_form.html.erb
  app/views/trips/edit.html.erb
  app/views/trips/index.html.erb
  app/views/trips/new.html.erb
  app/views/trips/show.html.erb
  config/locales/address/pt-BR.yml
  config/locales/defaults/pt-BR.yml
  config/locales/guide/messages/pt-BR.yml
  config/locales/guide/views/pt-BR.yml
  config/locales/trip/views/pt-BR.yml
  spec/factories/guides.rb
  spec/factories/trips.rb
  spec/models/guide_spec.rb
  spec/models/trip_spec.rb
  spec/routes/users_spec.rb
  yarn.lock
Labels: feature

#121 Room/validate adjust
  Gemfile
  Gemfile.lock
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/layouts/application.html.erb
  app/views/rooms/_form.html.erb
  app/views/rooms/_room.html.erb
  app/views/rooms/edit.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/new.html.erb
  app/views/rooms/show.html.erb
  config/locales/defaults/pt-BR.yml
  config/locales/room/messages/pt-BR.yml
  spec/controllers/rooms_controller_spec.rb
  spec/factories/rooms.rb
  spec/models/room_spec.rb
  spec/support/sample_photo_room.png
Labels: documentation, feature, request

#122 Bugfix/details structures
  app/models/structure.rb
  app/views/structures/_form.html.erb
  app/views/structures/index.html.erb
  app/views/structures/show.html.erb
  config/locales/structure/messages/pt-BR.yml
Labels: bug
